# Generated by Django 3.2.16 on 2023-01-18 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0009_alter_reservation_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation_manager.userprofile'),
        ),
    ]
