# Generated by Django 3.2.16 on 2023-01-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_manager', '0011_alter_reservation_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(default=1010101010222, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
